# Program 2 - Numpy Basics

In this programming assignment you will complete the following ten tasks related to numpy.  

In [2]:
import numpy as np

#### Question 1: 
Given an input numpy array, return a reversed numpy array.


In [16]:
def question_one():
    
    array = np.array([1, 2, 3, 4, 5, 6])
    
    # returns reversed numpy array with indexing
    return array[::-1]

# do not change the code below    
question_one()

array([6, 5, 4, 3, 2, 1])

**Expected Output**: 
<table>
    <tr> 
        <td> array([6, 5, 4, 3, 2, 1]) </td> 
    </tr>
</table> 

#### Question 2

Given an input numpy array, return the most frequent value in the NumPy array.

Hint: You may 
- Apply `bincount()` method of NumPy to get the count of occurrences of each element in the array.
- Apply `argmax()` method to get the value having a maximum number of occurrences(frequency).

In [14]:
def question_two():
    
    array = np.array([8,2,3,4,5,1,2,1,1,1, 8, 9, 100])
    
    # returns the most frequent value using the argmax function 
    # on the result of the bincount function
    return np.argmax(np.bincount(array))

# do not change the code below    
question_two()

1

#### Question 3

Given two input numpy arrays, stack them horizontally, return the resulting merged numpy array.

Hint: You may
- make two arrays be compatible when merging, i.e., make the shape of b be (3,1)
- use `hstack` or `concatenate` 

In [13]:
def question_three():
    
    a = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
    b = np.array([10, 20, 30])
    
    # reshapes b to the shape of (3, 1) then retuns a stacked with b

    return np.hstack((a, b.reshape(3, 1)))

# do not change the code below  
question_three()

array([[ 1,  2,  3, 10],
       [45,  4,  7, 20],
       [ 9,  6, 10, 30]])

**Expected Output**: 
<table >
    <tr> 
        <td> array([[ 1,  2,  3, 10],
 [45,  4,  7, 20],
 [ 9,  6, 10, 30]]) </td> 
    </tr>
</table> 

#### Question 4
Given an input numpy array, select rows [0,1,3,4] (0-index based) (i.e., row 2 should be discarded), return the resulting numpy array.

Hint: You may use fancy indexing 

In [12]:
def question_four():
    
    arr = np.array([[1, 20, 3, 1], 
                [40, 5, 66, 7], 
                [70, 88, 9, 11],
                [80, 100, 50, 77],
                [34, 28, 97, 52]])
    
    # Returns all rows except the 2nd row using fancy indexing
    return arr[(0, 1, 3, 4), ]

# do not change the code below  
question_four()

array([[  1,  20,   3,   1],
       [ 40,   5,  66,   7],
       [ 80, 100,  50,  77],
       [ 34,  28,  97,  52]])

**Expected Output**: 
<table >
    <tr> 
        <td>array([[  1,  20,   3,   1],
       [ 40,   5,  66,   7],
       [ 80, 100,  50,  77],
       [ 34,  28,  97,  52]]) </td> 
    </tr>
</table> 

#### Question 5

Given two input numpy arrays, compute matrix multiplication, return the resulting numpy array.

In [10]:
def question_five():
    
    a = np.array([[1, 2], [2, 3], [4, 5]])
    b = np.array([[4, 5, 1], [6, 7, 2]])
  
    # Uses dot function to return the resulting array of matrix multiplication
    return np.dot(a, b)

# do not change the code below  
question_five()

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

**Expected Output**: 
<table >
    <tr> 
        <td>array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]]) </td> 
    </tr>
</table> 

#### Question 6

Given an input numpy array, select row indices, where all elements in that row are positive, and return them. For instance, we have a two-d array with the shape of (4,5)

arr = np.array([

    [1,2,3,4,5],    # all elements >0, so we will include 0 
    [10,-3,30,4,5], # not all elements>0, so we will not include
    [3,2,5,-4,5],   # not all elements>0, so we will not include    
    [9,7,3,6,5]])   # all elements>0, so we will include 3

The result should be [0, 3]

Hint: You may
- use np.where 
- use `np.all` to check each row, use the option of axis=1, so that you can check all elements for any row 

See a similar example [here](https://www.geeksforgeeks.org/get-row-numbers-of-numpy-array-having-element-larger-than-x/) 

In [56]:
def question_six():
    
    arr = np.array([[19,52,3,48,5], 
      [30,-3,30,4,5], 
      [36,62,45,-4,5], 
      [69,47,3,-6,5],
      [4,78,24, 45, 39]])
    
    
    # returns indicies of rows with a value less than 0
    return np.where(np.all(arr>0, 1))

# do not change the code below  
question_six()

(array([0, 4], dtype=int64),)

**Expected Output**: 
<table >
    <tr> 
        <td>(array([0, 4], dtype=int64),) </td> 
    </tr>
</table> 

#### Question 7
For a given numpy array, find the indices of the sorted elements (ascending order) for each row using `argsort()`.

For instance, we have a two-d array with the shape of (4,3)

arr = np.array([

    [10, 20, 30],   # they are sorted already, so [0,1,2]
    [60, 50, 40],   # 40 (index 2), 50 (index 1), 60 (index 0), so [2,1,0]
    [80, 70, 90],   # 70 (index 1), 80 (index 0), 90 (index 2), so [1, 0, 2]
    [120,100,110]]) # 100 (index 1), 110 (index 2), 120 (index 0), so [1, 2, 0]
    
Hint: use axis option

In [57]:
def question_seven():
    
    arr = np.array([[10, 20, 30], 
                    [60, 50, 40],
                    [80, 70, 90],
                    [120,100,110]]) 
    
    # Uses the argsort function to return the indicies of the elements if they were to be sorted
    return np.argsort(arr)

# do not change the code below  
question_seven()

array([[0, 1, 2],
       [2, 1, 0],
       [1, 0, 2],
       [1, 2, 0]], dtype=int64)

**Expected Output**: 
<table >
    <tr> 
        <td>array([[0, 1, 2],
       [2, 1, 0],
       [1, 0, 2],
       [1, 2, 0]], dtype=int64)</td> 
    </tr>
</table> 

#### Question 8

Given an input array, return the **largest two** elements.

Hint:
 - use `sort()` then retrieve the largest two

In [9]:
def question_eight():
    
    arr = np.array([23, 12, 100, 37, 99, 2, 15, 76, 45, 92])
    
    # Sorts the array, then uses indexing to return the last 2 values
    return np.sort(arr)[-2:]

# do not change the code below  
question_eight()

array([ 99, 100])

#### Question 9

Given an input 2-d array, calculate the **sum of all columns**, and return the sum values.

For instance, we have a two-d array with the shape of (4,3)

arr = np.array([
    
    [1, 2, 3],                 
    [4, 5, 6],
    [7, 8, 9], 
    [10, 11, 12]])
    
    The sum of the first column: is 1+4+7+10=22
    The sum of the second column: is 2+5+8+11=26
    The sum of the third column: is 3+6+9+12=30
    
so the result should be [22,26, 30]


In [8]:
def question_nine():
    
    arr = np.array([[1, 2, 3], 
                    [4, 5, 6],
                    [7, 8, 9], 
                    [10, 11, 12]])
    
    # uses sum function on arr with axis 0, which adds all the columns, then returns the sums
    return np.sum(arr, 0)

# do not change the code below  
question_nine()

array([22, 26, 30])

#### Question 10

Given an input 2-d array, replace all negative values with 0

Hint: use `np.where()`

In [5]:
def question_ten():
    
    arr = np.array([[19,52,3,48,5], 
      [30,-3,30,4,5], 
      [36,62,45,-4,5], 
      [69,47,3,-6,5],
      [4,78,24, 45, 39]])
    
    # Uses where function to replace all negative values with 0, then returns new array
    arr = np.where(arr < 0, 0, arr)
    print(arr)
    return arr

# do not change the code below  
question_ten()

[[19 52  3 48  5]
 [30  0 30  4  5]
 [36 62 45  0  5]
 [69 47  3  0  5]
 [ 4 78 24 45 39]]


array([[19, 52,  3, 48,  5],
       [30,  0, 30,  4,  5],
       [36, 62, 45,  0,  5],
       [69, 47,  3,  0,  5],
       [ 4, 78, 24, 45, 39]])

**Expected Output**: 
<table >
    <tr> 
        <td>array([[19, 52,  3, 48,  5],
       [30,  0, 30,  4,  5],
       [36, 62, 45,  0,  5],
       [69, 47,  3,  0,  5],
       [ 4, 78, 24, 45, 39]])</td> 
    </tr>
</table> 